### ISSUE TITLE
Incorrect signature of `GrB_Matrix_diag`

### ISSUE THREAD

**Issue by eriknw** [DrTimothyAldenDavis/GraphBLAS#116]
According to the GraphBLAS C API version 2.0.0, the signature for `GrB_Matrix_diag` should be:
```C
1946 GrB_Info GrB_Matrix_diag(GrB_Matrix *C,
1947                          const GrB_Vector v,
1948                          int64_t k);
```
Note that this functions _creates_ a new matrix C.  This matrix is square with each dimension the size `size(v) + |k|` and the same datatype as v.

The first argument in SuiteSparse:GraphBLAS is currently `GrB_Matrix C`.  Fwiw, I like `GxB_Matrix_diag` better.

**Comment by DrTimothyAldenDavis** [comment]
Fixed in v7.0.0, to be released shortly. I have conformed GrB_Matrix_diag to the spec.
