### ISSUE TITLE
Iteration on bitmap vectors doesn't use the bitmap to skip values

### ISSUE THREAD

**Issue by eriknw** [DrTimothyAldenDavis/GraphBLAS#129]
Given a bitmap vector `v` where `v.nvals < v.size`, iteration over `v` performs `v.size` number of iterations.  I would expect it to iterate `v.nvals` number of times.

Bitmap matrices work as expected for me (i.e., it respects the bitmap).

**Comment by DrTimothyAldenDavis** [comment]
Ouch ... yes, that's a bug.  Fixing it now.

**Comment by DrTimothyAldenDavis** [comment]
Fixed in v7.0.2.  Thanks for the catch!

Can you give it a try?  I haven't tagged it as a release yet, but it's the latest version on the stable and master branches.

**Comment by eriknw** [comment]
Great!  I'm busy tonight, but I'll try to test it tomorrow.

**Comment by DrTimothyAldenDavis** [comment]
See this tag prerelease: https://github.com/DrTimothyAldenDavis/GraphBLAS/releases/tag/v7.0.2.beta1

**Comment by eriknw** [comment]
This works for me 🚀 !

**Comment by DrTimothyAldenDavis** [comment]
Fixed in v7.0.2, just released as a stable version.
