### ISSUE TITLE
GrB_eraseElement

### ISSUE THREAD

**Issue by victorstewart** [DrTimothyAldenDavis/GraphBLAS#14]
Is there any specific reason why there isn't an erase function? And can we get one in a future release?

**Comment by DrTimothyAldenDavis** [comment]
Do you mean GrB_Matrix_removeElement?  It's a function in the v1.2 spec
that I added in June 26, 2020, in version v3.3.0.

**Comment by victorstewart** [comment]
oh amazing! Sorry I was looking at the user guide which I see now is 2.2.2.
