### ISSUE TITLE
Matrix_extractElement_Structural

### ISSUE THREAD

**Issue by Wimmerer** [DrTimothyAldenDavis/GraphBLAS#142]
I think we discussed this on Slack Tim, but could we get an `extractElement_Structural` which tells me whether an index is stored? _Ideally_ this would be done as the output, not a ref to a boolean for speed purposes. Just return `GrB_SUCCESS` or `GrB_NO_VALUE`, which avoids allocating the output entirely.

I think this could be reasonably made a GrB function at some point.

**Comment by DrTimothyAldenDavis** [comment]
Yes, that would be easy to add.  Not sure what I should call it though.  GxB_Matrix_isElement maybe?  I don't want to confuse it with GrB_Matrix_extractElement_* since the signature would be very different.

**Comment by Wimmerer** [comment]
It's `isstored` in Julia. `isElement` I think is almost as good (I like the idea of stored and non-stored, but I don't know if that's part of the GraphBLAS "vocab" as much as `Element` is).

**Comment by DrTimothyAldenDavis** [comment]
The C API states this on page 95.  Note the wording "no stored value...".

> 4.2.4.12 Matrix_extractElement: Extract a single element from a matrix
> Extract one element of a matrix into a scalar."
> ...
> Return values
> GrB_SUCCESS   In blocking or non-blocking mode, the operation completed suc- cessfully. This indicates that the compatibility tests on dimensions and domains for the input arguments passed successfully, and the output scalar, val or s, has been computed and is ready to be used in the next method of the sequence.
> 
> GrB_NO_VALUE  When using the transparent scalar, val, this is returned when there is no stored value at specified location.

The spec uses the phrase "stored values" consistently. For example GrB_Matrix_nvals returns the number of stored values.  
But it doesn't use the word "stored" in any of the function names.

**Comment by DrTimothyAldenDavis** [comment]
See the draft update for v7.1.0 just posted on the master branch, with two new functions: GxB_Matrix_isStoredElement and GxB_Vector_isStoredElement.  It's passing my basic tests.  I'll post a stable v7.1.0 once all my brutal tests are done.  In the meantime, you could give it a try.

I didn't use the name 'isElement' because in the C API Specification, an element can have a stored value, or it might not.  It is still an element even if it isn't stored.  So I picked the name 'GxB_*_isStoredElement'.

**Comment by Wimmerer** [comment]
Perfect, I'll give it a try late tonight

**Comment by Wimmerer** [comment]
This works for me.
