### ISSUE TITLE
ISEQ monoids

### ISSUE THREAD

**Issue by Wimmerer** [DrTimothyAldenDavis/GraphBLAS#159]
In testing I realized there's no easy way to check that a Vector has all entries the same right? I believe we're missing the `IS_EQ` monoids. 

What the identity for that operation is, I have no idea.

**Comment by DrTimothyAldenDavis** [comment]
IS_EQ cannot be a monoid.  EQ cannot be a monoid either.

**Comment by Wimmerer** [comment]
Can we have a special reduction using the EQ binaryOp? One that doesn't throw Not Implemented?

**Comment by DrTimothyAldenDavis** [comment]
it won't work.  It doesn't fit mathematically into a monoid.

**Comment by Wimmerer** [comment]
Is there a method to compare the entries of a vector / matrix to ensure they're all eq? Other than unpacking?

**Comment by DrTimothyAldenDavis** [comment]
I think you could try this idea:  compute the min, and the max, and check if they are equal.  That would be pretty fast and require no new memory.

**Comment by DrTimothyAldenDavis** [comment]
I have an internal function that does this:  Source/GB_iso_check.c and Source/Template/GB_iso_check_template.c.  But there's no API for this to give to the user.

**Comment by DrTimothyAldenDavis** [comment]
I also have GxB_Matrix_iso and GxB_Vector_iso.  But they just return true if I already store the matrix as iso-valued.  Sometimes a matrix can have all values the same but I haven't detected it yet.
