### ISSUE TITLE
Growing size of compiled shared library

### ISSUE THREAD

**Issue by bergkvist** [DrTimothyAldenDavis/GraphBLAS#18]
Not sure this is something that is easy to do anything about, but the size trend of the shared library seems to be blowing up:
- v3.3.3 => 71MB uncompressed, 31MB compressed
- v4.0.0draft4 => 109MB uncompressed, 40MB compressed
- v4.0.0draft5 => 448MB uncompressed, 135MB compressed

This matters when including prebuilt graphblas libraries in docker images (where the image size is important)

For reference, I've published the docker images here:
https://hub.docker.com/r/graphblas/graphblas

---

```dockerfile
# Dockerfile/how the images are built:
FROM ubuntu:20.04 as builder
ENV DEBIAN_FRONTEND=noninteractive
RUN apt-get update && apt-get install -yq cmake make wget

ARG VERSION

WORKDIR /home/build
RUN wget https://github.com/DrTimothyAldenDavis/GraphBLAS/archive/v$VERSION.tar.gz
RUN tar -xf v$VERSION.tar.gz

WORKDIR /home/build/GraphBLAS-$VERSION
RUN make JOBS=8 && make install

FROM scratch
COPY --from=builder /usr/local/lib/ /usr/local/lib/
COPY --from=builder /usr/local/include/ /usr/local/include/
```

**Comment by DrTimothyAldenDavis** [comment]
v4.0.0draft5 was tagged only so I have a point where I know that started
adding the CUDA kernels.
Debug is enabled, so that might be one reason the compiled code is large.
I don't recommend that you
add any pre-release version to docker.

**Comment by bergkvist** [comment]
Makes sense that debug being enabled could explain the size of the compiled code.

Yeah, I agree that the pre-releases should not be "used in production". 

Having the drafts easily available through docker could provide value for people/researchers who want to experiment with the latest experimental/bleeding edge features. Compiling from source on a weak laptop can take a long time.

I guess it could also provide some value in terms of catching problems early, before it makes it into a stable release. Sort of how people using Gentoo/Arch Linux works as a "frontline defence", catching most problems before they make it into a stable distribution like Debian/CentOS etc. Not sure how well this analogy applies to this.

**Comment by DrTimothyAldenDavis** [comment]
Sure thing ... as long  as someone doesn't try to benchmark it ... (perhaps
add a comment to that).

When compiled with -O3, the code size drops to 132MB.  Big, but not as bad
as 400MB.  I'll try trimming it down.
There are more semirings I can disable (they still work and are still
visible to the user, just slower; see
GB_control.h).

**Comment by bergkvist** [comment]
Alright, I added the note "This pre-release is compiled in debug mode, and not optimized for size or performance.":

![image](https://user-images.githubusercontent.com/410028/97768164-89850900-1b21-11eb-9de3-e7fe6e6a6c25.png)

**Comment by DrTimothyAldenDavis** [comment]
looks great -- thanks!

**Comment by DrTimothyAldenDavis** [comment]
The soon-to-appear v4.0.1 will be about 112MB in size, when compiled in Release mode.  I might try to shrink it a bit, by removing more of the fast implementations of infrequently-used semirings (see Source/GB_control.h).
