### ISSUE TITLE
Size of Static Library

### ISSUE THREAD

**Issue by victorstewart** [DrTimothyAldenDavis/GraphBLAS#187]
even with the symbols stripped (which aren't a large % of the binary size) the static library is almost 200MB. even using LTO my executable is still 191694320 bytes.

just wondering if you've ever given this thought or concern RE instruction cache misses, and if there might ever be any way to strip the library to a subset of the massive permutations of operations and types, most of which i assume most aren't used by any given program?

**Comment by imciner2** [comment]
What is the linker command you are using to generate the final executable? Do you know if the `--whole-archive` option is being passed during the linker stage accidentally?

**Comment by victorstewart** [comment]
these are all the relevant cmake commands

`set(CMAKE_EXE_LINKER_FLAGS "-fuse-ld=lld -Xlinker -v -s")`
`target_compile_options(graph.database PUBLIC -stdlib=libc++ -mrdrnd -fno-exceptions)`
`target_compile_options(graph.database PUBLIC -w -Ofast -flto -frename-registers -fno-signed-zeros -fno-trapping-math)`
`target_link_libraries(graph.database PUBLIC ${NAMETAG_LIB_DIR}/libgraphblas.a)`

**Comment by imciner2** [comment]
Thanks, but can you provide the actual linker command line? You can find it in the link.txt file in the appropriate subdirectory of the build directory (probably the folder `CMakeFiles/graph.database.dir).

**Comment by victorstewart** [comment]
got it

`/usr/local/bin/clang++ -fuse-ld=lld -Xlinker -v -s CMakeFiles/graph.database.dir/graph.database.cpp.o -o graph.database  /root/x/libraries/lib/mimalloc-override.o -lc++ -ldl -lpthread /root/x/libraries/lib/liburing.a /root/x/libraries/lib/libgraphblas.a /root/x/libraries/lib/libgomp.a`

**Comment by victorstewart** [comment]
i realized `-flto` wasn't being passed to the linker. added it to the linker flags. but still same sized binary output.

**Comment by victorstewart** [comment]
i guess the first question is... am i the only one who has 200MB binaries? if so then there's some omitted option in my compilation/linking.

**Comment by DrTimothyAldenDavis** [comment]
The binary is large...  using gcc 9.4.0 on Ubuntu 20.04, I get a libgraphblas.so of 171MB.

I have reduced the # of pre-compiled kernels, using GraphBLAS/Source/GB_control.h, but the binary is still pretty large.  I've added new algorithmic variants (for each semiring), for example.  This speeds up GraphBLAS quite a bit, but makes for a larger binary.

I'll see what I can do to reduce the size.  In the meantime, it's possible to trim it by revising the Source/GB_control.h file.

**Comment by victorstewart** [comment]
@DrTimothyAldenDavis 

all i care about is performance, so the binary size is irrelevant to me.

just upon discovering that, thought it might warrant a discussion because it's 1 to almost 2 orders of magnitude larger than what i was used to dealing with.

it might be a great target for Facebook's binary layout optimization tool (https://github.com/facebookincubator/BOLT). TLDR; profile your executable then reorder it to improve locality. i'll play around with this in the coming weeks.

**Comment by DrTimothyAldenDavis** [comment]
Yes, I know it's large.  In the long run, and JIT will reduce the size drastically.  That's what I'm using for the CUDA kernels.  In the short run, I could disable some of the semirings and operators via GB_control.h.  Everything disabled there still works ... it's just slower, by using my 'generic' methods.  The generic methods use the same kernel templates, but all operations are done via function pointers.  That's how I handle user-defined ops and data types, for example.  Much more compact but a lot slower.

**Comment by victorstewart** [comment]
oh this GB_control file is great, thanks!

i'm going to dig into this. i only use a small subset of the available types, so i imagine i can shrink it enormously.

**Comment by imciner2** [comment]
@victorstewart sorry for the wild goose chase in the linking flags, I thought LLVM had put dead code elimination into LLD by default, but I guess they haven't done that.

The control header does look very nice, but I think my only concern is it works in the negative (pass a macro to disable). This means if someone wants to turn off all but a few types, they have to continually keep their compile definitions updated as new types are added to the library (since those would be on by default). Some sort of positive enablement would be useful, but I guess that might not be a concern if there isn't a plan to add a lot more types to the library.

**Comment by DrTimothyAldenDavis** [comment]
You can also do this via command line flags, like -DGB_NO_UINT16 for example, to disable all uint64_t types, operators, and semirings.

I'm very slow in adding new operators and data types.  If I do add them, I'll only add a subset of all possible semirings that can be built with them, via a default GB_control.h.

**Comment by DrTimothyAldenDavis** [comment]
If you disable a type, operator, or semiring that you are actually using in an algorithm, you can detect this via the 'burble'.  Just do GxB_set (GxB_BURBLE, true), and then look for the word 'generic'.  If you see that then either you've disabled a semiring/op/type in use, or you're using a non-built-in operation.  Typecasting leads to 'generic'.  For example if you do C=A*B using the plus_times_fp64 semiring, but B is fp32, then I must typecast, so I use the generic method (and it's a lot slower, maybe 3x to 4x or so).

If you don't see 'generic' coming up in the burble output, after modifying GB_control.h, then you haven't disabled any types/ops/semirings that are in use.

**Comment by DrTimothyAldenDavis** [comment]
I'm also having a related issue, with a command line that cmake generates being too long for MSVC on Windows when using the ninja makefile generator (see https://github.com/DrTimothyAldenDavis/GraphBLAS/issues/194 posted by @mmuetzel .

I could probably fix this with shorter filenames (which would not affect the library size, but would reduce the command line length).  I could also disable all INT16 and UINT16 methods, and even remove their files (which would reduce the size of the binary library, and reduce the # of files to compile).  A user application that uses the INT16 or UINT16 operators would still work, it would just be slower.  I don't know of anyone using those data types.

Or I could do both.

Currently, I can disable methods using this file:  https://github.com/DrTimothyAldenDavis/GraphBLAS/blob/stable/Source/GB_control.h .  However, the disabled operators are still compiled; they just become stubs that return the "not implemented" error code.  If I get that return value, I call my generic methods that use function pointers.  Slower, but they can handle anything.

The GB_control.h file reduces the library size, but it doesn't reduce the # of files to compile.

I'll have to ponder a solution for a future release.

**Comment by DrTimothyAldenDavis** [comment]
I've added this issue to a Project for the future SuiteSparse v7.1.0: https://github.com/users/DrTimothyAldenDavis/projects/1
