### ISSUE TITLE
GraphBLAS initialization and separate calls in Python wrapper

### ISSUE THREAD

**Issue by rustam-azimov** [DrTimothyAldenDavis/GraphBLAS#19]
I build the c++ library with 2 functions: f1 and f2. After that I call them from python wrapper using ctypes.

In f1 I call GrB_init(GrB_NONBLOCKING); and do some computations on GraphBLAS matrices with user-defined type. f1 return the pointer to the c++ class with these matrices. to the python wrapper 

After that I try to call function f2 from python wrapper and use this class and GraphBLAS matrices, but I get segmentation fault (core dumped) when I try to use GraphBLAS matrices.

Is there a way to init GrapBLAS in one call from wrapper and continue to use matrices in next calls. Or here we have some limitations?

**Comment by rustam-azimov** [comment]
Solved by calling GrB_init(GrB_NONBLOCKING) as separate function f0 in wrapper.

**Comment by DrTimothyAldenDavis** [comment]
I'm not sure I understand the issue.  GrB_init should be called just once,
before any other GrB* function.  If you call a GrB* function without
calling GrB_init, it should safely return an error code of GrB_PANIC.  It
shouldn't segfault, unless you are ignoring the error codes returned from
GraphBLAS.  Do f1 and f2 share the same global memory space?  GrB_init sets
some settings in a global space, which should be shared if you want to use
GraphBLAS matrices across two functions f1 and f2.

**Comment by rustam-azimov** [comment]
f1 and f2 in c++ share the same global memory space. They called from compiled library in python wrapper in one module. And yes, in f2 I ignored the error codes from GraphBLAS.
