### ISSUE TITLE
Where is `GxB_Context_error`?

### ISSUE THREAD

**Issue by eriknw** [DrTimothyAldenDavis/GraphBLAS#216]
Is it because the only time context functions fail is when the Context argument is invalid in some way or uninitialized?

**Comment by DrTimothyAldenDavis** [comment]
I should add it, but it would just return an empty string, just like GrB_Type_error, etc.  See the "empty" value assignment for these methods:  https://github.com/DrTimothyAldenDavis/GraphBLAS/blob/master/Source/GrB_error.c .

Only GrB_Scalar_error, GrB_Vector_error,  GrB_Matrix_error, and GrB_Descriptor_error can return an error string.

**Comment by DrTimothyAldenDavis** [comment]
I'll add this to v8.0.1.

**Comment by eriknw** [comment]
Added in v8.0.1. Closing.
