### ISSUE TITLE
Why was `nthreads` and `chunks` remove from the descriptor?

### ISSUE THREAD

**Issue by eriknw** [DrTimothyAldenDavis/GraphBLAS#218]
First, I'm sorry for not taking a closer look at the 8.0 draft releases (but you can see I [started to back in late March](https://github.com/GraphBLAS/python-suitesparse-graphblas/pull/76)). I thought there would be beta releases to more closely review and try.

Anyway, removing nthreads and chunks from the descriptor and adding them to context is a backwards-incompatible change that I would expect to be given a heads-up about (the stability of SuiteSparse:GraphBLAS has spoiled us!). We can more-or-less handle this in `python-graphblas`, but it's awkward to keep our current syntax which we like. For example, we can do `A.reduce_scalar().new(nthreads=8)` and `C(nthreads=4) << A @ B`. This syntax can easily support options that other implementations may have, and continues to support SuiteSparse-specific descriptors. Now, the most natural way to spell this in Python is:
```python
with Context(nthreads=8):
    C << A @ B
```
which is fine and we will also support this, but I don't like _forcing_ this verbose (it requires multiple lines) syntax when we already have a perfectly nice and concise syntax. This is also (currently) very SuiteSparse:GraphbLAS-specific, so it will be more difficult to handle multiple implementations in Python. (We'll see what happens with Context in the C API).

So, how terrible would it be to support `nthreads` and `chunks` in the descriptor again, which would take priority over the engaged context?

Side note: I also find it awkward that contexts aren't stacked (if I understand correctly), such as:
```python
with Context(nthreads=8) as c1:
    # nthreads is 8
    ....
    with Context(nthreads=4) as c2:
        # nthreads is 4
        ....
    # Now nthreads is from the global context, but c1 (nthreads=8) would be more natural
    ...
```

**Comment by DrTimothyAldenDavis** [comment]
Sorry for the confusion about the draft/beta.

It would be really terrible to try to put nthreads and chunk back into the descriptor.  It's just not compatible with the idea of the GxB_Context.  I considered keeping them (for backward compatibilty, as you mention) but it was just too hard to do.  Added to this complexity is that not all GrB methods even have a descriptor.  I didn't make that decision lightly since it did remove a feature I used to have.  It was always a nasty feature because it was so limited (not all methods had a descriptor, and it would be hard to write code (say in LAGraph) that used lots of descriptors (for GrB things), all of which would need to use the same nthreads and chunk.

For the syntax of A.reduce_scalar().new(nthreads=8), can you create a new Context just for this reduction, then free it when done?

For stacking contexts:  I don't think that would be possible.  Or at least, it would likely make kernel fusion (in the future) harder to do (and it's already hard enough).

Can you create a stack of Contexts in Python?

**Comment by eriknw** [comment]
Gotcha. Thanks for explaining. Feel free to close this issue (or I may close it in a bit).

> Can you create a stack of Contexts in Python?

We can do anything in Python! So, yeah, we'll manage. We'll figure out how we want contexts to behave (Python users have expectations!), and we can make it work even if we don't follow the semantics of SuiteSparse:GraphBLAS.

One function that I think would be super-convenient would be `GxB_Context_dup`. For example, this would make it easy to layer contexts such as having the first context set `nthreads` and another context set `nchunks`, and using context values from _both_ of them (i.e., in this case, the second context would be created by duplicating the first).

> For the syntax of A.reduce_scalar().new(nthreads=8), can you create a new Context just for this reduction, then free it when done?

The short answer is yes, but a challenge/question is what to do when there's already an engaged context.

> It would be really terrible to try to put nthreads and chunk back into the descriptor.

Hard to do or hard to use (you seemed to indicate both)? I know the limitations and challenges of having nthreads _only_ in the descriptor. However, if it was in _both_ the descriptor and context, then LAGraph can use the context (as it deems appropriate). In Python, it would be easy to choose when to have it in the context or descriptor. But, like I said above, we can manage.

**Comment by DrTimothyAldenDavis** [comment]
> One function that I think would be super-convenient would be GxB_Context_dup. 

That could break things in the future.  For kernel fusion, I plan on keeping a list of pending calls to GrB_whatever inside the Context for a given thread (or the global context if there is just one user thread, perhaps).  That way, I know that no parallel access will occur to the list of pending calls to GrB_whatever that I've not yet computed.

If the Context is duplicated ... how would that work?  Maybe copy the Context but not the list of pending calls?  Seems a bit dangerous.

The same kind of concerns would occur about stacking contexts.  If a thread disengages a current context, that would indicate to me that I need to flush all pending operations in that context.  If instead a single user thread can have a stack of contexts that it owns, what do I do with all the pending operations?  I can't stack those.  Perhaps if a thread has a Context1 engaged and then doesn't disengage it but engages Context2, then I would move the list of pending operations from Context1 to Context2.

I haven't worked this all out yet but I think I can design kernel fusion to save the list of pending calls within the thread's context, and then use engage/disengage to indicate when a list of pending calls needs to be finished, or perhaps transferred to the next context.

Allowing a context to be duplicated could really complicate kernel fusion.

> > For the syntax of A.reduce_scalar().new(nthreads=8), can you create a new Context just for this reduction, then free it when done?

> 
> The short answer is yes, but a challenge/question is what to do when there's already an engaged context.

Two solutions: (1) It could be disengaged then re-engaged when the operation is done (like stacking).  (2) Or if the user thread already has a context engaged, the # of threads could be set to 8 (in this case) then set back to the original number of threads when done.  The same context would still be engaged.

> > It would be really terrible to try to put nthreads and chunk back into the descriptor.

> Hard to do or hard to use (you seemed to indicate both)? I know the limitations and challenges of having nthreads only in the descriptor. However, if it was in both the descriptor and context, then LAGraph can use the context (as it deems appropriate). In Python, it would be easy to choose when to have it in the context or descriptor. But, like I said above, we can manage.

Hard for me to implement.  The two methods for handling the # of threads and chunk factor conflict with each other.  What if the method has a descriptor passed in to it ... I need to figure out if the threads setting has been set, but what if it's set to the default?  What does that mean?  Use the context instead?  Use the global default ... ?  I just don't know how to reconcile all the gnarly edge cases.

**Comment by eriknw** [comment]
Closing.

My questions have been answered (thanks!), and no further action is expected.

I have contexts working nicely in `python-graphblas` in this PR: https://github.com/python-graphblas/python-graphblas/pull/456

**Comment by eriknw** [comment]
Also, I'm happy to continue discussing contexts and kernel fusion elsewhere. I have thoughts and opinions ;)
