### ISSUE TITLE
How to interpret larger than expected arrays in import/export

### ISSUE THREAD

**Issue by eriknw** [DrTimothyAldenDavis/GraphBLAS#23]
In version 4, the documentation says the size of arrays may be larger than expected.  For example, in export CSR, it says `Aj_size >= nvals(A)`.  Similarly, for FullR, `Ax_size >= nrows*ncols`.  If we're given an array larger than is expected, do we simply use the first `n` elements where `n` is the size we expect?  The documentation for this is unclear to me.  I understand the rationale of transferring control in O(1) time and memory if possible, which naturally exposes some underlying implementation details.

Similarly, are there any advantages to passing a larger-than-necessary array to import?

**Comment by DrTimothyAldenDavis** [comment]
If the array is larger than the bare minimum, the entries are in the same
place as when the space is at the bare minimum.  So for CSR and CSC, the
values are in Ax [0 ... nvals-1].

There's currently no advantage of passing in a bigger array.  I don't use
the extra space.   I might in the future, however, so I tried to place few
constraints on the API design.

**Comment by eriknw** [comment]
Thanks for clarifying!

**Comment by eriknw** [comment]
I'm curious, would there be any danger or cost to `realloc` the arrays to the expected size before returning them?

**Comment by DrTimothyAldenDavis** [comment]
There might be a cost.  Currently, I just export what I have, and most of
the time the size is tight and no realloc would be needed.

I hope to implement a memory pool, where I keep a handful of malloc'd or
calloc'd blocks for future use.  That pool would keep arrays in buckets of
powers of 2, or perhaps those plus half-way between (8, 12, 16, 24, 32,
etc).  This will be important for speeding up GraphBLAS when there are many
lightweight calls to satisfy, like in the BFS of the Road graph.

In addition, adding pending tuples to a graph incrementally can leave some
space in the graph, for future growth.

So if I realloc the space down, to make it as tight as possible, and the
matrix is reimported, I lose all the benefit of these 2 cases.
