### ISSUE TITLE
How to use GraphBLAS on CUDA?

### ISSUE THREAD

**Issue by Kangfei** [DrTimothyAldenDavis/GraphBLAS#26]
Hi,

I have install GraphBLAS on a cuda enabled machine and I can run the demos in Demo successfully on cpu. But How to use the library on cuda? Whether it has independent API w.r.t. cpu? 

Best,
Kangfei

**Comment by DrTimothyAldenDavis** [comment]
The CUDA kernels are in development.  None of them are ready for use.  They
will not require any changes to the API once they are in place, except for
control settings like I have now for GxB_set (GxB_NTHREADS, nthreads) to
set the # of threads to use in OpenMP.  I'll have similar controls for the
GPU.
