### ISSUE TITLE
New functions in v5.0.2 not externed with GB_PUBLIC

### ISSUE THREAD

**Issue by eriknw** [DrTimothyAldenDavis/GraphBLAS#40]
`GxB_Matrix_concat`, `GxB_Matrix_diag`, `GxB_Matrix_split`, `GxB_Vector_diag` were not externed with `GB_PUBLIC`.  I suspect this was a simple oversight.  Sorry for not checking this earlier!

**Comment by DrTimothyAldenDavis** [comment]
Oops... yes, that's an oversight.  I'll fix it and it will be in 5.0.3.

**Comment by eriknw** [comment]
Sounds good.  Do you have an ETA for 5.0.3?

Once we get better automated testing and building for [`python-suitesparse-graphblas`](https://github.com/GraphBLAS/python-suitesparse-graphblas), we should catch errors like this *before* you release.

**Comment by DrTimothyAldenDavis** [comment]
I just posted this fix in the master branch with the latest commit.  I could wait a few days to collect any more current issues.

**Comment by eriknw** [comment]
Cool, and no rush.  I was just curious :)

**Comment by DrTimothyAldenDavis** [comment]
Just posted v5.0.3 with this fix, and a few others.  Thanks!
