### ISSUE TITLE
Apple-Darwin: Undefined symbols for architecture arm64

### ISSUE THREAD

**Issue by Wimmerer** [DrTimothyAldenDavis/GraphBLAS#41]
This may be just a missing flag on my part. Cross compiling from Alpine Linux to aarch64-apple-darwin I get this command/error pair:

```
/opt/bin/aarch64-apple-darwin20-libgfortran5-cxx11/aarch64-apple-darwin20-clang --sysroot=/opt/aarch64-apple-darwin20/aarch64-apple-darwin20/sys-root  -Wno-pointer-sign  -O3 -DNDEBUG   -O3 -DNDEBUG -dynamiclib -Wl,-headerpad_max_install_names -compatibility_version 5.0.0 -current_version 5.0.2 -o libgraphblasdemo.5.0.2.dylib -install_name @rpath/libgraphblasdemo.5.dylib CMakeFiles/graphblasdemo.dir/Demo/Source/bfs5m.c.o CMakeFiles/graphblasdemo.dir/Demo/Source/bfs5m_check.c.o CMakeFiles/graphblasdemo.dir/Demo/Source/bfs6.c.o CMakeFiles/graphblasdemo.dir/Demo/Source/bfs6_check.c.o CMakeFiles/graphblasdemo.dir/Demo/Source/dpagerank.c.o CMakeFiles/graphblasdemo.dir/Demo/Source/dpagerank2.c.o CMakeFiles/graphblasdemo.dir/Demo/Source/drowscale.c.o CMakeFiles/graphblasdemo.dir/Demo/Source/get_matrix.c.o CMakeFiles/graphblasdemo.dir/Demo/Source/import_test.c.o CMakeFiles/graphblasdemo.dir/Demo/Source/ipagerank.c.o CMakeFiles/graphblasdemo.dir/Demo/Source/irowscale.c.o CMakeFiles/graphblasdemo.dir/Demo/Source/isequal.c.o CMakeFiles/graphblasdemo.dir/Demo/Source/mis.c.o CMakeFiles/graphblasdemo.dir/Demo/Source/mis_check.c.o CMakeFiles/graphblasdemo.dir/Demo/Source/mis_score.c.o CMakeFiles/graphblasdemo.dir/Demo/Source/prand.c.o CMakeFiles/graphblasdemo.dir/Demo/Source/random_matrix.c.o CMakeFiles/graphblasdemo.dir/Demo/Source/read_matrix.c.o CMakeFiles/graphblasdemo.dir/Demo/Source/simple_rand.c.o CMakeFiles/graphblasdemo.dir/Demo/Source/simple_timer.c.o CMakeFiles/graphblasdemo.dir/Demo/Source/tricount.c.o CMakeFiles/graphblasdemo.dir/Demo/Source/usercomplex.c.o CMakeFiles/graphblasdemo.dir/Demo/Source/wathen.c.o  -Wl,-rpath,/workspace/srcdir/GraphBLAS/build -lm libgraphblas.5.0.2.dylib -lm 
```

```
Undefined symbols for architecture arm64:
 "___divdc3", referenced from:
    _complex_div in usercomplex.c.o
    _complex_rdiv in usercomplex.c.o
    _complex_minv in usercomplex.c.o
 ld: symbol(s) not found for architecture arm64
 clang-11: error: linker command failed with exit code 1 (use -v to see invocation)
 make[3]: *** [CMakeFiles/graphblasdemo.dir/build.make:435: libgraphblasdemo.5.0.2.dylib] Error 1
```

Is there a way to avoid building the demo libraries altogether, perhaps in the next patch? I didn't see a flag for it in CMakeLists.txt. The other question is whether that symbol being undefined silently affects the complex types in the library?

**Comment by DrTimothyAldenDavis** [comment]
yikes, that's weird.  It won't help to avoid compiling the demos.  The
problem will come up in any program that uses GraphBLAS, because the
complex types are now built-in.

This used to work on the x86 Apples.  Does the arm64 C compiler not support
"double complex"?
See GraphBLAS.h where I define GxB_FC64_t.

I see you might be compiling with cxx, which is C++, not cc.  That can be a
problem, although it should work.
I have an #ifdef __cplusplus in GraphBLAS.h that selects the proper complex
data types.  I got all of GraphBLAS to
compile with the gcc++ compiler, in the alternative/Makefile.

**Comment by giordano** [comment]
> I see you might be compiling with cxx, which is C++, not cc.

No, the compiler is `aarch64-apple-darwin20-clang`, it's the C one

**Comment by Wimmerer** [comment]
I get that linker error only with the demos, which is why I wondered if the main library was somehow fine.

**Comment by DrTimothyAldenDavis** [comment]
I'm guessing that you're just not seeing the problem because that final linking would only occur in a final executable, not in a shared library. Can you try compiling a vanilla code that just does a complex divide?  All I'm doing is "z = x/y ;" for 3 complex doubles.  Try this code below, as a stand-alone main program.  That's all I'm doing to trigger the error you see from the compiler.

```
#include <math.h>
#include <stdio.h>
#include <complex.h>
#undef I
typedef float  complex GxB_FC32_t ;
typedef double complex GxB_FC64_t ;

#ifndef CMPLX
    // gcc 6.2 on the the Mac doesn't #define CMPLX
    #define GxB_CMPLX(r,i) \
    ((GxB_FC64_t)((double)(r)) + (GxB_FC64_t)((double)(i) * _Complex_I))
#else
    // use the ANSI C11 CMPLX macro
    #define GxB_CMPLX(r,i) CMPLX (r,i)
#endif

int main (void)
{
    GxB_FC64_t x = GxB_CMPLX (3,4) ;
    GxB_FC64_t y = GxB_CMPLX (2,-1) ;
    GxB_FC64_t z = x / y ;
    printf ("x: (%g,%g)\n", creal (x), cimag (x)) ;
    printf ("y: (%g,%g)\n", creal (y), cimag (y)) ;
    printf ("z: (%g,%g)\n", creal (z), cimag (z)) ;
    printf ("z should be (0.4,2.2)\n") ;
}

**Comment by Wimmerer** [comment]
```
cc test.c -v
clang version 11.0.1 (/home/ec2-user/.julia/dev/BinaryBuilderBase/deps/downloads/llvm-project.git 43ff75f2c3feef64f9d73328230d34dac8832a91)
Target: arm64-apple-darwin20
Thread model: posix
InstalledDir: /opt/x86_64-linux-musl/bin
 "/opt/x86_64-linux-musl/bin/clang-11" -cc1 -triple arm64-apple-macosx10.10.0 -Wundef-prefix=TARGET_OS_ -Werror=undef-prefix -Wdeprecated-objc-isa-usage -Werror=deprecated-objc-isa-usage -emit-obj -mrelax-all -disable-free -disable-llvm-verifier -discard-value-names -main-file-name test.c -mrelocation-model pic -pic-level 2 -mframe-pointer=non-leaf -fno-rounding-math -munwind-tables -faligned-alloc-unavailable -fcompatibility-qualified-id-block-type-checking -target-cpu apple-a7 -target-feature +neon -target-abi darwinpcs -fallow-half-arguments-and-returns -debugger-tuning=lldb -v -nostdinc++ -resource-dir /opt/x86_64-linux-musl/lib/clang/11.0.1 -isystem /opt/aarch64-apple-darwin20/aarch64-apple-darwin20/sys-root/usr/include/c++/v1 -isysroot /opt/aarch64-apple-darwin20/aarch64-apple-darwin20/sys-root -internal-isystem /opt/aarch64-apple-darwin20/aarch64-apple-darwin20/sys-root/usr/local/include -internal-isystem /opt/x86_64-linux-musl/lib/clang/11.0.1/include -internal-externc-isystem /opt/aarch64-apple-darwin20/aarch64-apple-darwin20/sys-root/usr/include -Wno-unused-command-line-argument -fdebug-compilation-dir /workspace/srcdir -ferror-limit 19 -stack-protector 1 -fblocks -fencode-extended-block-signature -fregister-global-dtors-with-atexit -fgnuc-version=4.2.1 -fmax-type-align=16 -fcolor-diagnostics -o /tmp/test-de9672.o -x c test.c
clang -cc1 version 11.0.1 based upon LLVM 11.0.1 default target x86_64-linux-musl
ignoring nonexistent directory "/opt/aarch64-apple-darwin20/aarch64-apple-darwin20/sys-root/usr/local/include"
ignoring nonexistent directory "/opt/aarch64-apple-darwin20/aarch64-apple-darwin20/sys-root/Library/Frameworks"
#include "..." search starts here:
#include <...> search starts here:
 /opt/aarch64-apple-darwin20/aarch64-apple-darwin20/sys-root/usr/include/c++/v1
 /opt/x86_64-linux-musl/lib/clang/11.0.1/include
 /opt/aarch64-apple-darwin20/aarch64-apple-darwin20/sys-root/usr/include
 /opt/aarch64-apple-darwin20/aarch64-apple-darwin20/sys-root/System/Library/Frameworks (framework directory)
End of search list.
 "/opt/bin/aarch64-apple-darwin20-libgfortran5-cxx11/ld64.aarch64-apple-darwin20" -dynamic -arch arm64 -headerpad_max_install_names -macosx_version_min 11.0.0 -syslibroot /opt/aarch64-apple-darwin20/aarch64-apple-darwin20/sys-root -o a.out -L/opt/aarch64-apple-darwin20/aarch64-apple-darwin20/lib /tmp/test-de9672.o -lSystem
Undefined symbols for architecture arm64:
  "___divdc3", referenced from:
      _main in test-de9672.o
ld: symbol(s) not found for architecture arm64
```

**Comment by Wimmerer** [comment]
I can compile on all the linux architectures, including aarch64. I can't test the file for anything but x86_64-linux but we're at the very least not hitting the linking error.

**Comment by giordano** [comment]
> I'm guessing that you're just not seeing the problem because that final linking would only occur in a final executable, not in a shared library. 

Our goal is to call into shared library from Julia.

`libgraphblas.dylib` for `x86_64-apple-darwin` doesn't reference the `divdc3` symbol at all, so I'm not sure how this symbol can create problems.

**Comment by DrTimothyAldenDavis** [comment]
Great to hear you're working on GraphBLAS from Julia!

I would focus on getting that simple stand-alone test.c to work.  If that fails with __divdc3 not found, then GraphBLAS will fail too.  I don't have a way of disabling support for the complex types, since now even MS Visual Studio supports complex types.  In the past, I had to #ifdef around the complex data types but now they work "everywhere" ... except sadly the M1 macOS it appears.

**Comment by Wimmerer** [comment]
Yep! We had emailed previously about a Julia wrapper. I've got all the functions auto-wrapped, working on making them "Julian" by the end of this week with dispatch.

**Comment by DrTimothyAldenDavis** [comment]
Oh wait ... I do have my own complex divide .. See Source/GB_math.h for GB_divcomplex.  I forgot I had that there.  I use it to create 2 complex divide functions: GB_FC64_div and GB_FC32_div.   I have to do that for Windows, and it's more accurate on Linux too (MathWorks likes to have very accurate complex division).  I use that throughout GraphBLAS, even when the compiler can do z=x/y.

You could either skip the usercomplex demo, or tweak it.  I have guards around the complex operations, "if GxB_STDC_VERSION >= 201112L".  Your compiler must be passing that test but it shouldn't.  You could augment that #if test to disable the complex_div function in usercomplex.c.

**Comment by DrTimothyAldenDavis** [comment]
I will post an update shortly that skips the build of the demos.  They should probably be disabled by default anyway.  LAGraph is becoming the better place for demos and tests anyway.

**Comment by DrTimothyAldenDavis** [comment]
Regarding Julia:  yes, I remember our conversation a few months ago.  Julia is still high on my radar; I've just been caught up with other things.  Now that v5.x is out, I'm getting closer to looking at it again.

**Comment by DrTimothyAldenDavis** [comment]
I've added an option in the CMakeLists.txt to skip compiling the demos.  If you have a suggestion for a flag that is set by default on this Apple M1 macOS Arm build, please let me know.  I could revise the guard around the complex operations in the Demo/usercomplex.c, so that the demos could still compile on that system.

**Comment by DrTimothyAldenDavis** [comment]
See the latest push to the master branch: 
https://github.com/DrTimothyAldenDavis/GraphBLAS/commit/7071ddd50449cbee22a93ec109a2abbbcb88c291

**Comment by Wimmerer** [comment]
Thank you! We're still looking into what's happening. It *seems* like divdc3 is hiding behind an OS flag which isn't working properly with Clang. 

That being said I don't think this is something too worrisome. It's only happening in cross-compilation. We had someone compile actually on an M1 mac and it worked fine, and it works cross-compiling with gcc as well. And I doubt many people outside of us will be cross-compiling to macos. This is probably a wacky corner case to ignore.

**Comment by DrTimothyAldenDavis** [comment]
OK.  We can leave the #if guard in usercomplex.c as it stands.  I added a
flag in the CMake to control whether or not the demos are to be compiled.
I think it would make more sense if they were disabled by default.  Now
"make all" compiles them but "make" alone just does the library.  I will
make this change for v5.0.3.

**Comment by DrTimothyAldenDavis** [comment]
I just posted v5.0.3 which should fix this issue.  Can you give it a try?

**Comment by Wimmerer** [comment]
Yes things are working for me now. https://github.com/JuliaPackaging/Yggdrasil/pull/2938 looks like everything builds! Thanks for your help!

**Comment by DrTimothyAldenDavis** [comment]
Great!  Let me know if you need any additional help with GraphBLAS in Julia.

**Comment by szarnyasg** [comment]
A remark on Apple Silicon / M1-compatibility -- I tried building SuiteSparse:GraphBLAS in Rosetta:
- v6.1.0 failed on `list_cpu_features`
- v6.1.1 compiles (thanks to #82)

**Comment by DrTimothyAldenDavis** [comment]
@szarnyasg : thanks for checking that!  I don't have access to Apple silicon.
