### ISSUE TITLE
GCC 11.1 fails with -Werror=misleading-indentation

### ISSUE THREAD

**Issue by matzeri** [DrTimothyAldenDavis/GraphBLAS#42]
Buillding with GCC 11.1 **-Werror=misleading-indentation** stops at:

/pub/devel/suitesparse/suitesparse-5.9.0-1.i686/build/GraphBLAS/Source/Generated/GB_AxB__any_first_int32.c:278:5: 
error: this ‘if’ clause does not guard... [-Werror=misleading-indentation]
  278 |     if (exists && !cb) cx = (ax) ; cb |= exists

Is it a misunderstanding of the compiler or a real code issue ?

**Comment by DrTimothyAldenDavis** [comment]
Can you try with the SuiteSparse:GraphBLAS v5.0.3?  It should be fine with gcc 11 but I can't test with that compiler.

**Comment by matzeri** [comment]
I will try as soon I finish to update the rest of Suitesparse 5.9.0 as Cygwin packages.  Give me few days.
I tried the GCC 11.1 as for the i686 architecture the GCC 10.2.0 was crashing, the x64_86 had no problem.
 
It was long time I missed to update the packages 
https://sourceware.org/pipermail/cygwin/2016-March/226766.html
but the current Makefiles are much more easy to patch than the old structure, so it seems only a time consuming exercise.
The Cmake of Mongoose and GraphBLAS look fine, for the time being.

**Comment by DrTimothyAldenDavis** [comment]
Thanks for the feedback.  I hope to create cmake's for all packages in
SuiteSparse,
and then tie all of them together as well, to handle the dependencies
between them.
