### ISSUE TITLE
Masking groups of rows/cols in a matrix

### ISSUE THREAD

**Issue by luleg** [DrTimothyAldenDavis/GraphBLAS#48]
Hello,
I am quite new with GraphBlas so I may have missed something but I could not find an easy way to remove/mask groups of rows and/or columns from a matrix. Formally, I got a sparse vector, says U (containing integers but actually all equal to 1), and I want to remove rows or columns of a matrix A where U has no entry. In Matlab, something like : `A.*U` or` U.*A` woul work well. In GraphBlas, I am currently going with 
-Creating a matrix `Du = diag(u)`
-Compute `A*Du` or `Du*A`
Is there another, more efficient way for performing this ?
Thanks

**Comment by DrTimothyAldenDavis** [comment]
That would be a good way to do it in GraphBLAS.  For C=A*D, use the
ANY_FIRST semiring, unless you want a symbolic result (all entries in the
sparsity pattern of C equal to 1) in which case use the ANY_PAIR semiring.
For C=D*A use the ANY_SECOND or ANY_PAIR.  The FIRST, SECOND, and PAIR
operators do not have to read the values of D.

I have a new function, GxB_Matrix_diag, that converts a sparse vector into
a sparse matrix.  It's in v5.0.2 and later.  The spec is adding a similar
GrB_Matrix_diag, which will also work, once I add it.

It's possible that GrB_extract might be faster than mxm for this case,
particularly if you want to do C=D1*A*D2 at the same time.  That would
require you to do GrB_extractTuples from D1 and D2, or use GxB_export
(which is faster than extractTuples, but it destroys D1 and D2).  I'm also
writing a variant of export/import called unpack/pack, which will be
simpler to use than import/export.

**Comment by luleg** [comment]
Thanks a lot for your quick and clear reply. I already used the good semiring and GxB_Matrix_diag for building D1 and D2. As you guessed, I actually need to compute D1*A*D2. Using extract instead of mxm divided my runtime by 5 to 7, which is great! Thanks again.
