### ISSUE TITLE
unpack/pack functions sometimes switch ncols and nrows of the underlying Matrix

### ISSUE THREAD

**Issue by eriknw** [DrTimothyAldenDavis/GraphBLAS#53]
For example, if you unpack a Matrix via `FullR` and then pack it with `FullC`, then the shape of the Matrix is transposed.  I confirmed this by printing nrows and ncols after the unpack function, and they are reversed afterwards.

I have observed this reversing behavior with the following combinations of unpack-then-pack functions:

|unpack | pack |
|---------------------------|-------------------------|
| `GxB_Matrix_unpack_FullR`   | `GxB_Matrix_pack_FullC`   |
| `GxB_Matrix_unpack_FullC`   | `GxB_Matrix_pack_FullR`   |
| `GxB_Matrix_unpack_BitmapR` | `GxB_Matrix_pack_BitmapC` |
| `GxB_Matrix_unpack_BitmapC` | `GxB_Matrix_pack_BitmapR` |

Perhaps this is behaving as intended (I didn't read the fine print), but, nevertheless, I find it surprising that a pack operation can change the shape of a Matrix.

**Comment by DrTimothyAldenDavis** [comment]
Yes, that's a bug.  It's something I hadn't considered properly but it's a quick fix.  Thanks for catching it.

**Comment by DrTimothyAldenDavis** [comment]
I've posted a draft fix for this bug, on the master branch (not yet tagged).  It passes my basic tests and I'm running my longer, brutal tests now.  Once it passes those I'll tag it as v5.1.3 (beta), and once it passes your tests I'll call it v5.1.3 (stable).

**Comment by eriknw** [comment]
Excellent.  I'll test it now.

**Comment by eriknw** [comment]
It passes all of my tests.  Thanks.  Ship it!  🚀

**Comment by DrTimothyAldenDavis** [comment]
On its way.
