### ISSUE TITLE
Serialize and deserialize vectors and matrices

### ISSUE THREAD

**Issue by eriknw** [DrTimothyAldenDavis/GraphBLAS#6]
Hi Tim!  Is there a way to (de)serialize vectors and matrices to bytes or a stream of bytes?  I want to send these bytes over the wire, not to disk.

I am creating a Python library for doing distributed and/or out-of-core GraphBLAS computation using the `grblas` API.  A single distributed matrix is comprised of many SuiteSparse matrices (chunked any which way).  To have this work well in a distributed setting, the ability to serialize objects will of course be very valuable.  And just a heads up: this will also exercise running GraphBLAS with lots of user threads (fingers crossed!).

**Comment by DrTimothyAldenDavis** [comment]
Great question.  Short answer: Not yet.

It's something I think is missing from the C API Specification. It should
first be added as an experimental feature as a GxB* function, but I haven't
done that yet.  Ideally, it could optionally do compression as well, and it
could give you a series of chunks, one chunk of bytes at a time, if you
don't want to send the whole pile of bytes in a single message.  Then the
receiver, if it were running the same library (and version) of GraphBLAS,
could receive those bytes and reconstruct the matrix.

The best way to do this for now is to export the matrix/vector with
GxB*export*, so you have the full content.  Then you can ship the bytes,
and then use GxB*import* to import them back as GrB_matrix/GrB_Vector.  The
import/export takes O(1) time (they are like the C++ move constructors).

**Comment by eriknw** [comment]
Aha, thanks, I should be able to make that work!

**Comment by eriknw** [comment]
I'm curious, how do `GxB*import*` and `GxB*export*` handle zombie bits?  Is it always safe to go to/from standard CSC/CSR representation outside of GraphBLAS (such as if you wanted to export these to Matlab or numpy arrays)?

**Comment by DrTimothyAldenDavis** [comment]
I kill the zombies before I export the matrix.  Zombies don't have
passports so they can't cross the border; you have to be alive to go
through TSA security checkpoints :-)   Likewise pending tuples.

And you can't import a matrix with zombies or pending tuples, either.

**Comment by DrTimothyAldenDavis** [comment]
Regarding running lots of user threads in GraphBLAS:  this will get simpler in V4.0, when GrB_wait(void) is deleted.  Currently, to support GrB_wait() with no input arguments, I must maintain a global list of all matrices with pending work, even if those matrices are unrelated and constructed by independent user threads.  That's awkward.  When GrB_wait(void) is deleted, this global queue of pending matrices will be deleted, and then your user threads will not interact at all.

**Comment by eriknw** [comment]
Sounds much better.  Thanks for the info.  It seems natural to call `GrB_wait` with arguments.

I admit, I haven't yet stressed GraphBLAS with lots of user threads yet, but I'm eagerly pushing forward!

**Comment by victorstewart** [comment]
I wrote a graph database around GraphBLAS so i touched upon this when persisting my various matrices and vectors to disk as snapshots. this occurs either... 

A) during regular operation at various intervals
B) upon process shutdown
or C) when replicating the entire graph to a new instance

for matrices, this is the binary schema I write the data to disk according to (same idea for vectors):

nrows(8) ncols(8) nvec(8) ApSize(8) AhSize(8) AjSize(8) AxSize(8) sparsity(4) jumbled(1) (pad to 512 bytes) ApBytes(end 2MB aligned) AhBytes(end 2MB aligned) AjBytes(end 2MB aligned) AxBytes(end 2MB aligned)

I think the current way of export + import is actually optimal for **A)** and **B)** given the initial copy elision and freedom to write the bytes to disk however you please (i use io_uring with 2MB chunks and `nr_requests` in flight).

**C)** is a bit trickier. Ideally you could transform the matrices into a copy-on-write state, so that you can stream it over the network without needing to either take the database offline or copy the entire thing which may be memory prohibitive (which is why for the moment I elected to just serialize them all the disk and then use sendfile on a worker thread).

**Comment by DrTimothyAldenDavis** [comment]
Yes, the import/export is one step in the right direction towards a
serialize/deserialize pair of methods.  A better method would be one that
could just give you a set of opaque bytes, not the non-opaque ones from the
import/export.  That way, I could do things like compression/uncompression,
if you're sending data along a slow wire to another machine, for example.
I'm still considering some kind of serialize/deserialize but haven't
settled on an API design yet.

**Comment by eriknw** [comment]
All sounds good.  To @victorstewart's point, though, I agree that the current import/export is good enough and efficient enough to support my needs (I dup first then export the copy to leave the original untouched).  If I need to send the data over the wire, then the protocol I will be using already samples and compresses if appropriate.

**Comment by DrTimothyAldenDavis** [comment]
I now have a draft implementation of GxB_Matrix_serialize / deserialize, as well as the GrB versions from the draft v2.0 spec (but with some required modifications).  The draft v2.0 spec has some problems with it and I think will be updated soon.

My serialize/deserialize use lz4 or lz4hc, both for GrB and GxB versions.

These new functions are in the v5.2.0 alpha pre-release.  That version passes all my tests, but there are some features drafted but not yet tested (the new GrB_select) and some others not yet written (GrB_apply with the new GrB_IndexUnaryOp).

I won't post v5.2.0 as a stable release until the draft v2.0 spec stabilizes.  It will be pre-releases (v5.2.0 alphaN for N = 1, 2, ...) for a while.

**Comment by DrTimothyAldenDavis** [comment]
Serialization / deserialization is now fully tested in v5.2.0.alpha10, and the documentation is drafted.
