### ISSUE TITLE
Typecast mystery: value-dependent coercion weirdness with accumulate?

### ISSUE THREAD

**Issue by eriknw** [DrTimothyAldenDavis/GraphBLAS#7]
Using SuiteSparse:GraphBLAS 3.2.2.

I apologize for not having these examples in C (GraphBLAS is still building...).  Here's an example using `grblas` Python API.  I will explain some hidden details:
```python
w = gb.Vector.from_values([0, 1], [0, -20], dtype='INT64')
u = gb.Vector.from_values([0, 1], [1, 2], dtype='FP64')
w(accum=gb.binary.plus) << u
```
which results in
```python
                    0                    1
  4886396799603965952  4886405595696988140
```
As you can probably guess, `u` and `w` are length-two vectors.  `u` is FP64 dtype with values `1` and `2`.  `w` is INT64 dtype with values `0` and `-20`.

Under the hood, this is calling something like:
```C
GrB_apply(
    w,
    GrB_NULL,           // no mask
    GrB_PLUS_INT64,     // accum; the dtype is very important here!
    GrB_IDENTITY_FP64,  // unary op
    u,
    GrB_NULL            // no descriptors
)
```
Surprisingly, the results in `w` are `4886396799603965952` and `4886405595696988140`.

If we use `GrB_PLUS_FP64` for the accumulation instead, then we get the expected results `1` and `-18`.

Here's the kicker.  Let's extend `w` and `u` while keeping the first two elements the same:
```python
w = gb.Vector.from_values([0, 1, 2, 4, 5], [0, -20, 30, 40, 50], dtype='INT64')
u = gb.Vector.from_values([0, 1, 3, 4, 5], [1, 2, 3, -4, 0], dtype='FP64')
w(accum=gb.binary.plus) << u
```
which results in
```python
  0    1   2  3   4   5
  1  -18  30  3  36  50
```
These values are correct!  But, why don't the first two values match the first example?!?!

I'm quite confused and surprised, although it is very possible that I am doing something silly here.

**Comment by DrTimothyAldenDavis** [comment]
It might have to do with a compiler optimization.  I ran across an odd typecast from double to int, but not this one.  It was the case where the double was outside the range of a valid int, which gives an undefined result in ANSI C11.

Is your two-line printing of  a vector displaying the indices in the first line, and values in the 2nd?

It looks like a bug, in any case.  A standalone C example would be very helpful.

How are you printing the values?  I assume you force completion first?  Do you use extractTuples to get the values out, to print them?

**Comment by eriknw** [comment]
Yes, the first line displays the indices and the values are in the second line.

Yes, the values are gotten from extractTuples.  Also, Vector_build was used to populate the arrays.

I'm working on a C example and should probably try to verify I see this behavior with my local build.

**Comment by eriknw** [comment]
Bah, I just realized I compiled the wrong version.  I'll continue tomorrow.  I did verify the C call from Python though:
```python
import grblas as gb
w = gb.Vector.from_values([0, 1], [0, -20], dtype='INT64')
u = gb.Vector.from_values([0, 1], [1, 2], dtype='FP64')
gb.lib.GrB_Vector_apply(
    w.gb_obj[0],
    gb.base.NULL,
    gb.lib.GrB_PLUS_INT64,
    gb.lib.GrB_IDENTITY_FP64,
    u.gb_obj[0],
    gb.base.NULL
)
```
which gives the wonky results.  Here, `gb.base.NULL` is the null pointer.

If any observers are curious, one can install `grblas` via `conda install -c conda-forge grblas` on OS X and Linux (and conda from here: https://docs.conda.io/en/latest/miniconda.html).  It will be pip-installable soon (the normal way to install Python packages).

**Comment by DrTimothyAldenDavis** [comment]
I replicated the error.  That's a bug in 3.2.2 that I fixed in the 3.3.0 draft.  It was a typecasting mistake in Source/GB_dense_subassign_23.c for the generic case.  In 3.2.2, I picked the wrong typecasting function.  It's fixed in the draft of 3.3.0.

**Comment by DrTimothyAldenDavis** [comment]
In v3.2.2, this code below replicates the bug.  In v3.3.0, it gives the right result.

`#include "GraphBLAS.h"

#define OK(method)  \
{                   \
    info = method ; \
    if (info != GrB_SUCCESS) printf ("Error: %s\n", GrB_error ()) ; \
}

int main (void)
{

    GrB_Vector w, u ;
    GrB_Info info ;
    OK (GrB_init (GrB_NONBLOCKING)) ;
    OK (GxB_set (GxB_BURBLE, true)) ;
    OK (GrB_Vector_new (&w, GrB_INT64, 2)) ;
    OK (GrB_Vector_setElement_INT64 (w, 0, 0)) ;
    OK (GrB_Vector_setElement_INT64 (w, -20, 1)) ;
    OK (GrB_Vector_new (&u, GrB_FP64, 2)) ;
    OK (GrB_Vector_setElement_FP64 (u, 1, 0)) ;
    OK (GrB_Vector_setElement_FP64 (u, 2, 1)) ;
    OK (GxB_print (w, 3)) ;
    OK (GxB_print (u, 3)) ;
    OK (GrB_apply (w, NULL, GrB_PLUS_INT64, GrB_IDENTITY_FP64, u, NULL)) ;
    OK (GxB_print (w, 3)) ;
    OK (GrB_finalize ( )) ;
}
`

**Comment by DrTimothyAldenDavis** [comment]
I fixed the bug on June 1st, but I didn't log the bug fix in the Doc/ChangeLog. I've added that (bug #18) to the ChangeLog, in v3.3.0-draft10, just posted now.

**Comment by eriknw** [comment]
Great, thanks!
