### ISSUE TITLE
Static link GraphBLAS 6.1.3

### ISSUE THREAD

**Issue by AviAvni** [DrTimothyAldenDavis/GraphBLAS#88]
When trying to integrate GraphBLAS 6.1.3 to RedisGraph
We use the graphblas_static target and it look like cpu_features is not static linked
Trying to resolved it by adding the below code to `CMakeLists.txt` didn't help
```
if ( BUILD_GRB_STATIC_LIBRARY )
    target_link_libraries ( graphblas_static PUBLIC cpu_features )
endif ( )
```
the  linker error was resolved but at runtime we get `Symbol not found: _GetX86Info`

**Comment by DrTimothyAldenDavis** [comment]
I'm adding a compile-time flag that cmake will use to disable cpu_features entirely.  That will at least work around this issue, and it should be quick to fix, in a v6.1.4 release.  I will then try to figure out why this symbol isn't getting added properly to the libgraphblas.a.

**Comment by DrTimothyAldenDavis** [comment]
Can you give the v6.1.3.beta1 release a try?  It's at https://github.com/DrTimothyAldenDavis/GraphBLAS/releases/tag/v6.1.4.beta1 .

**Comment by AviAvni** [comment]
Thank you this version is verified and it compiled and work perfectly
