### ISSUE TITLE
Failing test (gbtest76) on Apple Silicon

### ISSUE THREAD

**Issue by szarnyasg** [DrTimothyAldenDavis/GraphBLAS#90]
I made some progress on porting the library to Apple Silicon (#84, #86). This issue documents how to build Octave v7 on macOS and run the test. Finally, it contains the output of a single failing test.

## Building Octave

1. Grab the brew formula:

    ```bash
    wget https://raw.githubusercontent.com/Homebrew/homebrew-core/master/Formula/octave.rb
    ```

1. Edit `octave.rb`
   1. Add `"disable-docs"` to `args` (or ensure that you have a working texinfo installation).
   1. Edit Mercurial (`hg`) repository: switch from the `default` branch (containing code for Octave v8.0) to `stable` (v7.0).
1. Run

    ```bash
    brew install --head ./octave.rb
    ```

    This takes about 10 minutes.

## Building the tests (gbmake)

1. Grab the OpenMP binaries as described at <https://mac.r-project.org/openmp/>:

    ```bash
    curl -O https://mac.r-project.org/openmp/openmp-13.0.0-darwin21-Release.tar.gz
    sudo tar fvxz openmp-13.0.0-darwin21-Release.tar.gz -C /
    ```

1. Run

    ```bash
    sed -i.bkp 's/-fopenmp/-Xclang -fopenmp/g' @GrB/private/gbmake.m
    ```

1. Run `octave` and follow the instructions in `GraphBLAS/README.md`, including `gbmake`:

    ```matlab
    cd @GrB/private
    gbmake
    ```

## Running the tests

Run the tests:

```matlab
cd test
gbtest
```

Currently, all tests pass except one.

## Failing test: gbtest76

[`gbtest76`](https://github.com/DrTimothyAldenDavis/GraphBLAS/blob/stable/GraphBLAS/test/gbtest76.m) fails on macOS / Apple Silicon. (I tried running it in both Octave 7 and 8 on macOS. It passes on Linux with Octave 8. I did not try it on Linux with Octave 7.)

The output of `gbtest76` is the following:

```matlab
> gbtest76

gbtest76: testing trig and special functions
single
double
single complex
double complex
error: assert (err == 0) failed
error: called from
    assert at line 107 column 11
    gbtest76>gbtest76b at line 432 column 5
    gbtest76 at line 47 column 13
```

Upon closer inspection, the only test case that fails is the following:
```matlab
case { 'double complex' }
    A = rand (4) + 1i* rand (4) ;
    B = rand (4) + 1i* rand (4) ;
    tol = 1e-10 ;
    G = GrB (A) ;
    H = GrB (B) ;
    gbtest76b (A, B, G, H, tol) ;
```

I printed the output before the assertion in line 432:
```matlab
C1 = A.^1 ;
C2 = G.^1 ;
err = norm (C1-C2, 1) ;
display (err)
assert (err == 0) ;
```

It indeed has a non-zero result:
```console
double complex
err = 2.7497e-16
```

**Comment by szarnyasg** [comment]
I printed the variables before the failed `assert` on both systems:

```matlab
    display (A)
    display (G)
    display (C1)
    display (C2)
    err = norm (C1-C2, 1) ;
    assert (err == 0) ;
```

Output on macOS:
```
A =

        0 +      0i   0.0228 + 0.9185i   0.2208 + 0.0581i   0.5036 + 0.2507i
   0.2106 + 0.3586i   0.4256 + 0.1694i   0.6469 + 0.6762i   0.0394 + 0.5968i
   0.8007 + 0.7316i   0.1015 + 0.6726i   0.3503 + 0.8454i   0.1009 + 0.4423i
   0.9370 + 0.8383i   0.2599 + 0.9665i   0.1803 + 0.3423i   0.9882 + 0.1748i


G =

  4x4 GraphBLAS double complex matrix, bitmap by col
  15 nonzeros, 15 entries, memory: 480 bytes

    (2,1)    0.210577 + 0.358555i
    (3,1)    0.800747 + 0.731598i
    (4,1)    0.936969 + 0.838327i
    (1,2)    0.0227826 + 0.918482i
    (2,2)    0.425619 + 0.169425i
    (3,2)    0.1015 + 0.672641i
    (4,2)    0.25992 + 0.966549i
    (1,3)    0.220829 + 0.0580509i
    (2,3)    0.646926 + 0.676202i
    (3,3)    0.350294 + 0.845425i
    (4,3)    0.180318 + 0.342313i
    (1,4)    0.503637 + 0.250687i
    (2,4)    0.0393787 + 0.596791i
    (3,4)    0.100921 + 0.442314i
    (4,4)    0.988235 + 0.174819i

C1 =

        0 +      0i   0.0228 + 0.9185i   0.2208 + 0.0581i   0.5036 + 0.2507i
   0.2106 + 0.3586i   0.4256 + 0.1694i   0.6469 + 0.6762i   0.0394 + 0.5968i
   0.8007 + 0.7316i   0.1015 + 0.6726i   0.3503 + 0.8454i   0.1009 + 0.4423i
   0.9370 + 0.8383i   0.2599 + 0.9665i   0.1803 + 0.3423i   0.9882 + 0.1748i


C2 =

  4x4 GraphBLAS double complex matrix, bitmap by col
  15 nonzeros, 15 entries, memory: 480 bytes

    (2,1)    0.210577 + 0.358555i
    (3,1)    0.800747 + 0.731598i
    (4,1)    0.936969 + 0.838327i
    (1,2)    0.0227826 + 0.918482i
    (2,2)    0.425619 + 0.169425i
    (3,2)    0.1015 + 0.672641i
    (4,2)    0.25992 + 0.966549i
    (1,3)    0.220829 + 0.0580509i
    (2,3)    0.646926 + 0.676202i
    (3,3)    0.350294 + 0.845425i
    (4,3)    0.180318 + 0.342313i
    (1,4)    0.503637 + 0.250687i
    (2,4)    0.0393787 + 0.596791i
    (3,4)    0.100921 + 0.442314i
    (4,4)    0.988235 + 0.174819i

error: assert (err == 0) failed
error: called from
    assert at line 107 column 11
    gbtest76>gbtest76b at line 441 column 5
    gbtest76 at line 50 column 13
```

**Comment by DrTimothyAldenDavis** [comment]
It's not an error at all.  Those differences are just round-off error.  The complex multiply/add/etc can differ slightly on different compilers.  I use  "assert(err==0)" if it seems appropriate, and if those fail with err of 1e-16, or so, I just replace it with "assert (err < 1e-12)" say.

**Comment by DrTimothyAldenDavis** [comment]
I do all my code updates on the master branch, not on the stable branch.  The stable branches don't get git commits very often, except for the next stable release.  Can you make your PR's go to that branch instead?  That would be a lot easier.  Thanks!

**Comment by DrTimothyAldenDavis** [comment]
I just revised this test ; see the gbtest76.m in the master branch.

**Comment by szarnyasg** [comment]
> I do all my code updates on the master branch, not on the stable branch. The stable branches don't get git commits very often, except for the next stable release. Can you make your PR's go to that branch instead? That would be a lot easier. Thanks!

Indeed, I should have targeted `master` and not `stable` -- sorry about that. I see that you performed the merge in a2ce979f8eee5f4e6a9a259932e2a8ca66759ca8.

Thanks for revising the gbtest76 test case!

I now tried running the Octave tests on 2682a3c58868383872c14b65e4f4543c874e938b but it failed due to a hard-coded x87 dependency in `GB_cpu_features` file:
```
octave:1> cd @GrB/private
octave:2> gbmake
Note that this @GrB interface is under the GNU GPLv3 (or later).
Hit enter to confirm and agree; control-C to decline:
.In file included from /Users/szarnyasg/git/GraphBLAS/GraphBLAS/@GrB/private/util/gb_abort.c:10:
In file included from util/gb_interface.h:17:
In file included from ../../../Source/GB_helper.h:16:
In file included from ../../../Source/GB.h:17:
In file included from ../../../Source/GB_cpu_features.h:61:
../../../cpu_features/include/cpuinfo_x86.h:252:2: error: "Including cpuinfo_x86.h from a non-x86 target."
#error "Including cpuinfo_x86.h from a non-x86 target."
 ^
1 error generated.
```

**Comment by DrTimothyAldenDavis** [comment]
Oops.  That #if was supposed to guard against it but I wrote it wrong.  See the next push on master.

**Comment by szarnyasg** [comment]
Thanks! It works now and the tests pass:
```
gbtest: all tests passed
```
