### ISSUE TITLE
Descriptor for GxB_Matrix_sort

### ISSUE THREAD

**Issue by eriknw** [DrTimothyAldenDavis/GraphBLAS#93]
In section 6.13.2 of the User Guide for `GxB_Matrix_sort`, you mention to use the descriptor `GrB_DESC_IN0`.  A descriptor of this name does not exist in GraphBLAS.h.  Do you mean `GrB_DESC_T0`?

**Comment by DrTimothyAldenDavis** [comment]
Oops.  That's correct, it should be GrB_DESC_T0.  Fixed.
